### PR TITLE
Adds support for embedded resources

### PR DESCRIPTION
**Pull request by Shazwazza**
This PR does the following:

* Allows nuPickers to keep using embedded resources for js/css so you can ship with a single file (assembly)
* Updates to latest CDF which is required with support for the new `IVirtualFileWriter` (etc... classes)
* Adds a very simple test web project to demonstrate the implementation of the `IVirtualFileWriter`
    * The modules section in the web.config must have runAllManagedModulesForAllRequests="true" - which currently is also true in the umbraco core. Without this the *.nu file path will not route when in debug mode
    * To see the JS requests being made in the demo web project you'll need to see them with chrome dev tools

This PR does not actually update all of the css/js resources for the property editors to support this, you'll have to manually do that by changing the PropertyEditorAsset for all JS/CSS files to be suffixed with a ".nu" file extension. For example, the following:

    [PropertyEditorAsset(ClientDependencyType.Javascript, EmbeddedResource.RootUrl + "Editor/EditorResource.js")]

would need to be changed to:

    [PropertyEditorAsset(ClientDependencyType.Javascript, EmbeddedResource.RootUrl + "Editor/EditorResource.js.nu")]

This PR also does not wire up the Umbraco startup handlers, currently the test website on startup needs to create a custom route using the nupickers code:

     RouteBuilder.BuildRoutes(routes);

This would need to be added to an umbraco startup handler to handle the ".nu" web requests when in debug mode.

### CODE REVIEW

**Comment by Jeavon** [comment]
Thanks Shannon. I made a few changes to allow for both requests with or without the .nu extension to be accepted so that we don't have to use the .nu extension for all the .html views and image assets. 
You can see my changes in the branch [here](https://github.com/uComponents/nuPickers/tree/Shazwazza-virtualizedfiles) One thing I didn't need to do was wire up the startup handlers as we had that [already](https://github.com/uComponents/nuPickers/blob/Shazwazza-virtualizedfiles/source/nuPickers/EmbeddedResourceStartup.cs)?
We also have AppVeyor build packages [here](https://ci.appveyor.com/project/JeavonLeopold/nupickers/build/artifacts) so we can get some testers on the case. I've tested a few editors in Umbraco v7.2.1 and all worked perfectly.
Is the intention to update Umbraco v7.2.3 to include CDF v1.8.3? If not we will need to include the CDF dlls in our Umbraco package.

**Comment by Shazwazza** [comment]
Yup, i'll make a task to have 7.2.3 running latest CDF so that should be fine.

Great news that it works! Let me know if you come up against any issues.

**Comment by Jeavon** [comment]
@Shazwazza is it to be expected that these .nu files are not bundled in to the Dependency handler when not in debug mode, they still get served as individual resources?

**Comment by Shazwazza** [comment]
Yup they should be

I think you are missing a startup handler, see this line:

https://github.com/uComponents/nuPickers/pull/83/files#diff-b07f69c55e13a804269fbb9b0bda5733R25


It's also worth noting that the *.nu extension will only work with RAMFAR (run all modules for all requests) enabled, if you want to have support without ramfar it would be tricky because you'd have to add custom http handlers with custom extensions. Otherwise a safe way to do it would be to use a *.nu.axd extension since that will already be mapped through ASP.Net

We're hoping to turn off RAMFAR by default in v8 btw since it's much better for performance, but we'll see.

**Comment by Shazwazza** [comment]
@Jeavon any success with this?

**Comment by Jeavon** [comment]
@Shazwazza yes, it works perfectly. We are just debating changing all the extensions to .nu.axd or adding a http handler, apart from that we should be able to release once Umbraco 7.2.3 with CDF 1.8.3 is released.

**Comment by Shazwazza** [comment]
You don't need a handler until v8 most likely because RAMFAR will be hard to disable currently without breaking some things (IIRC). 

Currently you are just using an MVC route for your stuff, you can keep that without a handler if you use an .axd extension. I think this is heaps easier than mucking around with the web.config and manually creating an IHttpHandler when an MVC controller is far easier to work with.

Make sense?

**Comment by Jeavon** [comment]
Yes, makes sense, I will change them all to .nu.axd and give it a try

**Comment by Jeavon** [comment]
Ok, so two issues with this change, if I change all the extensions to .nu.axd, in debug mode it works fine, but in release mode the files are not being combined. I wonder if CDF (maybe the AddWriterForExtension method) has a issue with the double dots in the extension (.nu.axd)? 
Second issue is that when I disable RAMFAR the paths don't work even with the .nu.axd extension.
Maybe a httphandler is the simplest way forward, thoughts?

**Comment by Jeavon** [comment]
@Shazwazza I decided to try out a httphandler and it works fine with or without RAMFAR as expected. 

Strangely, I accidentally discovered that leaving the MVC route in place, it takes precedence over the HttpHandler, so you can in fact add a jibberish http handler registration and then it works without RAMFAR and without needing a http handler. e.g.

`<add name="NuHandler" preCondition="integratedMode" verb="GET" path="*.nu" type="AnyThingYouLike" />`

Not sure I would recommend this approach though!

Anyhow as Umbraco v7 currently requires RAMFAR I think we are happy to release with just *.nu unless you think otherwise?

**Comment by Shazwazza** [comment]
Ok so potentially this would be far less hacky for your httphandler registration:

     <add name="NuHandler" preCondition="integratedMode" verb="GET" path="*.nu" type="System.Web.Mvc.MvcHandler" />

The type `System.Web.Mvc.MvcHandler` is what handles MVC stuff and it is in fact an IHttpHandler so that would be far nicer and not actually hacky.

Up to you though, with RAMFAR you don't have to worry about it and as i said i 'think' umbraco will require RAMFAR for a while yet.

**Comment by Jeavon** [comment]
@Shazwazza it seems that using this method causes a issue when upgrading Umbraco as the resources are not available during the install wizard. Has the ApplicationStarted event occurred during the upgrade wizard? More info in issue #107

**Comment by Shazwazza** [comment]
ApplicationStarted does not run if umbraco is not configured (i.e. not installed or requires upgrade)

If you want it to execute then, you need to override the methods on your startup handler... There are two methods you can override to execute when there is no db and when it's not configured.

**Comment by Jeavon** [comment]
@Shazwazza that's pretty cool, I will give it a try out

**Comment by Jeavon** [comment]
@Shazwazza this does the job but I'm wondering why the ExecuteWhenApplicationNotConfigured method get's called multiple times?

        protected override bool ExecuteWhenApplicationNotConfigured
        {
            get
            {
                if (RouteTable.Routes["nuPickersShared"] == null)
                {
                    RouteBuilder.BuildRoutes(RouteTable.Routes);
                    FileWriters.AddWriterForExtension(".nu", new EmbeddedResourceWriter());
                }
                return base.ExecuteWhenApplicationNotConfigured;
            }
        }

**Comment by Shazwazza** [comment]
This should literally return true or false. Under no circumstance should you be putting logic in that property.

**Comment by Shazwazza** [comment]
This is a BOOLEAN that simply indicates if your startup handler will execute or not if the application is not configured (i.e. installing or upgrading)

**Comment by Jeavon** [comment]
@Shazwazza makes a lot more sense! thanks!

**Pull request merged**
