### PR TITLE
Typeahead controls support all save formats

### PR DESCRIPTION
**Pull request by Alain-es**
Typeahead controls support all save formats: CSV, JSON, XML and Relations only

### CODE REVIEW

**Comment by Alain-es** [comment]
I have created this PR against the release branch because I am using this new feature in a production environment. If you need me to create a PR against the Master branch, please let me know.

**Comment by Hendy** [comment]
Hi Alain, thanks for the PR :+1: sorry for the delay, want to understand the consequences... I had actually previously removed the Relations Only and CSV formats from Typeahead pickers so as to ensure the saved data held both the id and the label text, the reason being that the data source could be vast and dependant on some 'typeahead text' to narrow that data down.

I can see how Relations Only would work, as we have a known data set, but not sure about the CSV only ?

**Comment by Alain-es** [comment]
Hi Hendy, for CSV and also for Json and XML, it retrieves the Keys of the picked (saved) items  using the method getSavedKeys() (I haven't modified this method).
When it gets all the picked (saved) items' keys, then it will call the method getEditorDataItemsByIds() which queries the data source (XML, lucene, SQL, ....) in order to retrieve all the labels.
After that it invokes the method saveFormatResource.getSavedItems() to format properly the retrieved items from the datasource (I haven't modified this method).

All of this is done by the code below in the EditorRejsource.js file (Line 48):

		var ids = saveFormatResource.getSavedKeys(model.value).join(",");
		dataSourceResource.getEditorDataItemsByIds(model, ids).then(function (response) {
			deferred.resolve(saveFormatResource.getSavedItems(response.data));
		});

Also note that whith this PR, when the JSON/XML format is set to saved picked items, if the picked items are modified using Umbraco, then they will automatically be updated in the nupickers controls!

**Comment by Hendy** [comment]
Hi @Alain-es sorry it's taking a while to get my head round these changes...

I can see that the typeahead text filters down the data-set just before it's returned, so my initial concerns about the potential for typeahead text potentially needing to exist in order to request the data aren't an issue with the built-in pickers, but other typeahead pickers could be problematic, eg. https://github.com/Hendy/nuPickers-FlickrPickers/blob/master/source/nuPickers-FlickrPickers/DataSources/PhotoSearch.cs#L69

In EditorResource.js, could we check for the existing save format to see if it stores both key  / label, and if so, use that (as before), else, if the save format is relations (still not convinced about CSV) what would be good would be to call a single method that in turn called the existing GetEditorDataItems (with flag to ignore any typeahead) and then filter these results by the keys (would mean moving code out of the Api controllers so that it could be called directly).

It's really quite complicated ! (much easier to just save as JSON / XML :))

Are you using it with relations only, or was there a reason to use CSV instead of the JSON / XML ?

Thanks again.
BTW, would it be OK to add your surname to the list of authors on:  https://www.nuget.org/packages/nuPickers ? we couldn't find it anywhere.

**Comment by Alain-es** [comment]
Hi Hendy,

Thanks for taking a look and for the suggestions.

I didn't know about other pickers like FlickrPicker. It could be very handy :)

I agree that if the existing save format stores both key / label then we retrieve these values. 
And when it is relations or csv then the values are retrieved from the datasource the way you suggested. I will work on that as soon as I get some spare time.

The reason I need the CSV format is because the project requires that the Ids are in the Lucene index. And XML/JSON formats are not an option because I need that labels are up to date if they are updated.

My surname is Mangin :)

Alain

**Comment by Alain-es** [comment]
I did some quick changes following your recommendations. But items are still filtered in the ApiController's methods. The reason is that I was wondering if it is a good idea filtering data items on the client side. In my case I have thousands of items, so I am concerned about the performance of sending such a large amount of data in order to filter maybe only 3 or 4 picked ítems. What do you think?
Please, note that I haven't had time to test it properly! I will do more testing on Monday/Tuesday.

Cheers,
Alain

**Comment by Alain-es** [comment]
Created new PR

**Pull request closed without merging**
