### PR TITLE
FIX for issue #85 to make it possible for the nupickers to be used in property editors that wrap other editors.

### PR DESCRIPTION
**Pull request by pgregorynz**
Changes the way that values are checked and passed when loading the property editor

### CODE REVIEW

**Comment by pgregorynz** [comment]
The main reason I made this fix was that I am using it inside the new DocType Grid Editor which wraps it.   Im sure others will try shortly now that it has been officially released.

**Comment by Hendy** [comment]
Hi @pgregorynz I've just re-tested each save format within a Nested Content both before and after these changes, and both seem to work !

Perhaps Nested Content has been updated to ensure it returns an object instead of a json string where relevant ? @leekelleher

Any chance you could re-test the current nuPickers release (1.4.0) with Nested Content (0.1.1) ?

Thanks

**Comment by pgregorynz** [comment]
hmmm thats stange.  Will see if anything has changed with the doctype grid.



On Mon, Mar 23, 2015 at 9:08 AM, Hendy Racher <notifications@github.com>
wrote:

> Hi @pgregorynz <https://github.com/pgregorynz> I've just re-tested each
> save format within a Nested Content both before and after these changes,
> and both seem to work !
>
> Perhaps Nested Content has been updated to ensure it returns an object
> instead of a json string where relevant ? @leekelleher
> <https://github.com/leekelleher>
>
> Any chance you could re-test the current nuPickers release (1.4.0) with
> Nested Content (0.1.1) ?
>
> Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/uComponents/nuPickers/pull/86#issuecomment-84730020>.
>



-- 

*Peter Gregory*
*little.web.empire*
www.littlewebempire.com


mobile: +61(0)400309500
skype: pgregorynz
twitter: pgregorynz

**Comment by Hendy** [comment]
ooh that could be it, I didn't try with the Doc Type Grid Editor, only Nested Content. (I know the existing code works with Archetype)

**Comment by Hendy** [comment]
@pgregorynz my mistake (I should have noticed your reference to the DocType Grid Editor package) and indeed this update does fix an issue when using a nuPicker on a docType within the Doc Type Grid Editor.

**Comment by mattbrailsford** [comment]
I think this could have actually be an issue with DTGE that has recently been fixed. See https://github.com/leekelleher/umbraco-doc-type-grid-editor/issues/3

**Pull request merged**
